collections:
  #- name: ansible.netcommon

  - name: ansible.network

  - name: ansible.posix
    source: https://galaxy.ansible.com

    #- name: ansible.scm

    #- name: ansible.security

    #- name: ansible.snmp

  - name: ansible.utils

    #- name: ansible.windows

  - name: community.general
    source: https://galaxy.ansible.com

    #- name: redhat.insights

  - name: redhat.rhel_idm

  - name: redhat.rhel_system_roles

    #- name: redhat.satellite

    #- name: redhat.satellite_operations

  - name: vmware.vmware

