collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=9.0.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

  - name: redhat.rhel_system_roles

  - name: vmware.vmware
#ansible.posix            1.5.4
#redhat.rhel_system_roles 1.23.0
#vmware.vmware            1.1.0
