---
- hosts: all
  gather_facts: True
  become: True
  serial: 1

  collections:
    - redhatinsights.insights
    - community.general

  tasks:
    - name: RedHat RHSM System Subscribe
      community.general.redhat_subscription
        state: present
        auto_attach: true
        username: "{{ lookup('credential', '(redhat) Subscription Management', 'username') }}"
        password: "{{ lookup('credential', '(redhat) Subscription Management', 'password') }}"
      when: ansible_distribution == 'RedHat' and ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'

    - include_role:
        name: insights_client
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'
